// export const CONTACTS_MOCK = [
//   {
//     name: 'Juan',
//     lastname: 'Hernández',
//     email: 'juan.perez@mail.com',
//     numbers: ['5512345678', '5598765432'],
//     addresses: [
//       {
//         street: 'Calle Ficticia 123',
//         noExt: '202',
//         city: 'Ciudad de México',
//         state: 'CDMX',
//         zip: '01234',
//         country: 'México',
//       },
//       {
//         street: 'Avenida Siempre Viva 456',
//         noExt: '301',
//         city: 'Guadalajara',
//         state: 'Jalisco',
//         zip: '45000',
//         country: 'México',
//       },
//     ],
//   },
//   {
//     name: 'María',
//     lastname: 'Gómez Sánchez',
//     email: 'maria.gomez@mail.com',
//     numbers: ['3323456789'],
//     addresses: [
//       {
//         street: 'Avenida Chapultepec 789',
//         noExt: '303',
//         city: 'Monterrey',
//         state: 'Nuevo León',
//         zip: '64000',
//         country: 'México',
//       },
//     ],
//   },
//   {
//     name: 'Carlos',
//     lastname: 'Rodríguez Ruiz',
//     email: 'carlos.rodriguez@mail.com',
//     numbers: ['3334567890', '3387654321'],
//     addresses: [
//       {
//         street: 'Calle Larga 101',
//         noExt: '305',
//         city: 'Puebla',
//         state: 'Puebla',
//         zip: '72000',
//         country: 'México',
//       },
//     ],
//   },
//   {
//     name: 'Ana',
//     lastname: 'Martínez García',
//     email: 'ana.martinez@mail.com',
//     numbers: ['2224567890'],
//     addresses: [
//       {
//         street: 'Calle Juárez 890',
//         noExt: '308',
//         city: 'Tijuana',
//         state: 'Baja California',
//         zip: '22000',
//         country: 'México',
//       },
//     ],
//   },
//   {
//     name: 'Luis',
//     lastname: 'Fernández Pérez',
//     email: 'luis.fernandez@mail.com',
//     numbers: ['5556789012', '5576543210'],
//     addresses: [
//       {
//         street: 'Calle del Sol 123',
//         noExt: '311',
//         city: 'Mérida',
//         state: 'Yucatán',
//         zip: '97000',
//         country: 'México',
//       },
//     ],
//   },
//   {
//     name: 'Carmen',
//     lastname: 'Sánchez Torres',
//     email: 'carmen.sanchez@mail.com',
//     numbers: ['6646789012'],
//     addresses: [
//       {
//         street: 'Avenida Reforma 456',
//         noExt: '313',
//         city: 'Cancún',
//         state: 'Quintana Roo',
//         zip: '77500',
//         country: 'México',
//       },
//     ],
//   },
//   {
//     name: 'Fernando',
//     lastname: 'López Ramírez',
//     email: 'fernando.lopez@mail.com',
//     numbers: ['9997890123'],
//     addresses: [
//       {
//         street: 'Calle Hidalgo 123',
//         noExt: '315',
//         city: 'León',
//         state: 'Guanajuato',
//         zip: '37000',
//         country: 'México',
//       },
//     ],
//   },
//   {
//     name: 'Patricia',
//     lastname: 'García Pérez',
//     email: 'patricia.garcia@mail.com',
//     numbers: ['6647890123'],
//     addresses: [
//       {
//         street: 'Avenida Constitución 789',
//         noExt: '318',
//         city: 'Querétaro',
//         state: 'Querétaro',
//         zip: '76000',
//         country: 'México',
//       },
//     ],
//   },
//   {
//     name: 'Miguel',
//     lastname: 'Martínez López',
//     email: 'miguel.martinez@mail.com',
//     numbers: ['7777890123'],
//     addresses: [
//       {
//         street: 'Calle Reforma 789',
//         noExt: '320',
//         city: 'Culiacán',
//         state: 'Sinaloa',
//         zip: '80000',
//         country: 'México',
//       },
//     ],
//   },
//   {
//     name: 'Laura',
//     lastname: 'Sánchez Gómez',
//     email: 'laura.sanchez@mail.com',
//     numbers: ['9987654321'],
//     addresses: [
//       {
//         street: 'Calle 10',
//         noExt: '322',
//         city: 'Mazatlán',
//         state: 'Sinaloa',
//         zip: '82110',
//         country: 'México',
//       },
//     ],
//   },
// ]
export const FAKE_CONTACTS = [
  {
    name: 'David',
    lastname: 'Llanes Bojorquez',
    email: 'david1@example.com',
    numbers: ['6681995997'],
    addresses: ['Calle Maravillas 725, Los Mochis, Sinaloa, México'],
  },
  {
    name: 'Maria',
    lastname: 'Gonzalez',
    email: 'maria2@example.com',
    numbers: ['6671234567', '6672345678'],
    addresses: ['Avenida del Sol 123, Culiacán, Sinaloa, México'],
  },
  {
    name: 'Juan',
    lastname: 'Perez',
    email: 'juan3@example.com',
    numbers: ['6698765432'],
    addresses: [
      'Calle Central 456, Mazatlán, Sinaloa, México',
      'Calle Secundaria 789, Mazatlán, Sinaloa, México',
    ],
  },
  {
    name: 'Ana',
    lastname: 'Lopez',
    email: 'ana4@example.com',
    numbers: ['6649876543'],
    addresses: [
      'Boulevard Independencia 321, Tijuana, Baja California, México',
    ],
  },
  {
    name: 'Carlos',
    lastname: 'Hernandez',
    email: 'carlos5@example.com',
    numbers: ['6631239876', '6633456789'],
    addresses: ['Calle Primera 101, Mexicali, Baja California, México'],
  },
  {
    name: 'Luisa',
    lastname: 'Martinez',
    email: 'luisa6@example.com',
    numbers: ['6621112222'],
    addresses: [
      'Avenida Libertad 654, Hermosillo, Sonora, México',
      'Calle Ejemplo 12, Hermosillo, Sonora, México',
    ],
  },
  {
    name: 'Miguel',
    lastname: 'Santos',
    email: 'miguel7@example.com',
    numbers: ['6612223333'],
    addresses: ['Avenida Reforma 500, Ensenada, Baja California, México'],
  },
  {
    name: 'Elena',
    lastname: 'Gutierrez',
    email: 'elena8@example.com',
    numbers: ['6653334444', '6654445555'],
    addresses: ['Calle Segunda 77, Tecate, Baja California, México'],
  },
  {
    name: 'Roberto',
    lastname: 'Navarro',
    email: 'roberto9@example.com',
    numbers: ['6645556666'],
    addresses: ['Calle Ejemplo 111, Tijuana, Baja California, México'],
  },
  {
    name: 'Sofia',
    lastname: 'Mendez',
    email: 'sofia10@example.com',
    numbers: ['6627778888'],
    addresses: ['Boulevard Kino 300, Hermosillo, Sonora, México'],
  },
  {
    name: 'Pedro',
    lastname: 'Torres',
    email: 'pedro11@example.com',
    numbers: ['6686667777', '6687778888'],
    addresses: ['Calle Principal 456, Los Mochis, Sinaloa, México'],
  },
  {
    name: 'Laura',
    lastname: 'Ramos',
    email: 'laura12@example.com',
    numbers: ['6658889999'],
    addresses: ['Calle Nueva 321, Tecate, Baja California, México'],
  },
  {
    name: 'Jorge',
    lastname: 'Castillo',
    email: 'jorge13@example.com',
    numbers: ['6670001111'],
    addresses: ['Avenida Hidalgo 789, Culiacán, Sinaloa, México'],
  },
  {
    name: 'Patricia',
    lastname: 'Figueroa',
    email: 'patricia14@example.com',
    numbers: ['6641112233'],
    addresses: [
      'Calle Secundaria 123, Tijuana, Baja California, México',
      'Avenida Principal 456, Tijuana, Baja California, México',
    ],
  },
  {
    name: 'Ricardo',
    lastname: 'Salazar',
    email: 'ricardo15@example.com',
    numbers: ['6693334444'],
    addresses: ['Calle Puerto 555, Mazatlán, Sinaloa, México'],
  },
  {
    name: 'Martha',
    lastname: 'Ortiz',
    email: 'martha16@example.com',
    numbers: ['6619998888', '6618887777'],
    addresses: ['Avenida Siempre Viva 742, Ensenada, Baja California, México'],
  },
  {
    name: 'Luis',
    lastname: 'Garcia',
    email: 'luis17@example.com',
    numbers: ['6684445555'],
    addresses: ['Calle Libertad 101, Los Mochis, Sinaloa, México'],
  },
  {
    name: 'Isabel',
    lastname: 'Camacho',
    email: 'isabel18@example.com',
    numbers: ['6632223333'],
    addresses: ['Calle Ejemplo 456, Mexicali, Baja California, México'],
  },
  {
    name: 'Antonio',
    lastname: 'Rios',
    email: 'antonio19@example.com',
    numbers: ['6625556666'],
    addresses: ['Boulevard Principal 123, Hermosillo, Sonora, México'],
  },
  {
    name: 'Gabriela',
    lastname: 'Suarez',
    email: 'gabriela20@example.com',
    numbers: ['6659990000'],
    addresses: ['Calle Nueva 789, Tecate, Baja California, México'],
  },
]
